/**
 * Revflow V2 — Batch Recovery Evaluation Service
 *
 * Evaluates portfolios and batches of failed payment transactions
 * against Revflow's diagnostic engine, Strategy Registry, ERV heuristic scoring,
 * Explicit Stopping Engine, and Policy Engine.
 *
 * PROVENANCE INVARIANT:
 * All results generated by this service are explicitly labeled as 'SIMULATED_BATCH'
 * or 'PORTFOLIO_EVALUATION'. They NEVER claim live Razorpay provider verification.
 */

const { STRATEGY_DEFINITIONS, getStrategy, EXECUTION_MODES } = require('../strategies/strategyRegistry');
const { calculateERV, computeBaseProbability, HEURISTIC_VERSION } = require('../strategies/expectedRecoveryValue');
const { evaluateStoppingCriteria, STOP_REASON_CODES } = require('../policy/stoppingEngine');
const { evaluatePolicy } = require('../policy/policyEngine');

const MAX_BATCH_SIZE = 500;

class BatchValidationError extends Error {
  constructor(message, statusCode = 400, details = null) {
    super(message);
    this.name = 'BatchValidationError';
    this.statusCode = statusCode;
    this.details = details;
  }
}

/**
 * Validates and normalizes raw batch input items.
 *
 * @param {Array} cases - Raw case input objects
 * @param {object} options
 * @returns {Array} Sanitized cases
 */
function validateBatchInput(cases, { maxBatchSize = MAX_BATCH_SIZE } = {}) {
  if (!Array.isArray(cases)) {
    throw new BatchValidationError('Batch payload must contain a "cases" array.', 400);
  }

  const requestedMax = Number(maxBatchSize);
  const effectiveMaxLimit = (Number.isInteger(requestedMax) && requestedMax > 0)
    ? Math.min(requestedMax, MAX_BATCH_SIZE)
    : MAX_BATCH_SIZE;

  if (cases.length > effectiveMaxLimit) {
    throw new BatchValidationError(`Batch size exceeds maximum limit of ${effectiveMaxLimit} items. Received: ${cases.length}.`, 413);
  }

  const seenPaymentIds = new Set();
  const validated = [];

  for (let i = 0; i < cases.length; i++) {
    const item = cases[i];
    if (!item || typeof item !== 'object') {
      throw new BatchValidationError(`Item at index ${i} is not a valid object.`, 400);
    }

    const paymentId = item.paymentId ? String(item.paymentId).trim() : null;
    if (!paymentId) {
      throw new BatchValidationError(`Item at index ${i} is missing required 'paymentId'.`, 400);
    }

    if (paymentId.length > 128) {
      throw new BatchValidationError(`Item at index ${i} has invalid 'paymentId': exceeds maximum length of 128 characters.`, 422);
    }

    if (seenPaymentIds.has(paymentId)) {
      throw new BatchValidationError(`Duplicate paymentId '${paymentId}' detected at index ${i}. Each batch item must be distinct.`, 422);
    }
    seenPaymentIds.add(paymentId);

    const amount = Number(item.amount);
    if (!Number.isSafeInteger(amount) || amount <= 0) {
      throw new BatchValidationError(`Item at index ${i} ('${paymentId}') has invalid amount: ${item.amount}. Must be a positive integer in paise.`, 422);
    }

    const currency = item.currency ? String(item.currency).trim().toUpperCase() : 'INR';
    if (currency !== 'INR') {
      throw new BatchValidationError(`Item at index ${i} ('${paymentId}') has unsupported currency: '${currency}'. Only INR is supported.`, 422);
    }

    // Never accept client-injected provider verification or execution claims
    validated.push({
      id: item.id || (i + 1),
      paymentId,
      orderId: item.orderId || `order_batch_${paymentId}`,
      amount,
      currency,
      riskLevel: ['HIGH', 'MEDIUM', 'LOW'].includes(item.riskLevel) ? item.riskLevel : 'MEDIUM',
      riskStatus: ['RECOVERABLE', 'SUPPRESSED', 'RESOLVED', 'OPEN'].includes(item.riskStatus) ? item.riskStatus : 'RECOVERABLE',
      failureReason: item.failureReason || 'gateway_timeout',
      customerReference: item.customerReference || null,
      paymentAttemptCount: Number.isInteger(item.paymentAttemptCount) ? Math.max(1, item.paymentAttemptCount) : 1,
      timeSinceFailureMinutes: Number(item.timeSinceFailureMinutes) >= 0 ? Number(item.timeSinceFailureMinutes) : 30,
      escalationStatus: ['NONE', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED'].includes(item.escalationStatus) ? item.escalationStatus : 'NONE',
      firstDetectedAt: item.firstDetectedAt || new Date().toISOString(),
      lastEventAt: item.lastEventAt || new Date().toISOString()
    });
  }

  return validated;
}

/**
 * Evaluates a single batch case through Revflow's diagnostic and policy pipeline.
 *
 * @param {object} item - Normalized case
 * @param {object} context
 * @returns {object} Case evaluation result
 */
function evaluateBatchItem(item, { isTestMode = true, confidenceThreshold, now = () => new Date() } = {}) {
  // 1. Base Probability & Heuristic Scoring
  const baseProb = computeBaseProbability({
    riskLevel: item.riskLevel,
    failureReason: item.failureReason,
    paymentAttemptCount: item.paymentAttemptCount,
    timeSinceFailureMinutes: item.timeSinceFailureMinutes
  });

  // 2. Candidate Strategy Selection
  // Default to CREATE_PAYMENT_LINK for transient failures, or SCHEDULE_RETRY_WINDOW for recurring
  let candidateAction = 'CREATE_PAYMENT_LINK';
  const reasonLower = (item.failureReason || '').toLowerCase();
  if (reasonLower.includes('insufficient_funds') || reasonLower.includes('mandate') || reasonLower.includes('subscription') || reasonLower.includes('renewal') || item.playbook === 'failed_subscription') {
    candidateAction = 'SCHEDULE_RETRY_WINDOW';
  } else if (item.amount > 2500000) {
    candidateAction = 'REQUEST_MANUAL_REVIEW';
  }

  const strategy = getStrategy(candidateAction);
  const frictionPaise = Math.round(item.amount * (strategy?.defaultFrictionRate || 0.05));
  const interventionCostPaise = strategy?.defaultInterventionCostPaise || 0;

  const ervPaise = calculateERV({
    amount: item.amount,
    probability: baseProb,
    interventionCost: interventionCostPaise,
    frictionCost: frictionPaise
  });

  const diagnosis = {
    diagnosis: {
      cause: `Identified ${item.failureReason} failure pattern`,
      confidence: baseProb,
      evidence: [{ field: 'payment.failureReason', value: item.failureReason }]
    },
    proposedAction: candidateAction,
    recommendation: {
      action: candidateAction,
      reason: `Selected ${strategy?.name || candidateAction} based on ERV ₹${(ervPaise / 100).toLocaleString('en-IN')}`
    },
    candidates: [{ action: candidateAction, score: baseProb }]
  };

  // 3. Stopping Criteria Evaluation
  const stopping = evaluateStoppingCriteria({
    recoveryCase: item,
    diagnosis,
    candidateAction,
    events: [{ eventType: 'payment.failed', paymentStatus: 'failed', failureReason: item.failureReason }],
    existingActions: [],
    now
  });

  // 4. Policy Engine Evaluation
  const policy = evaluatePolicy({
    recoveryCase: item,
    diagnosis,
    candidateAction,
    events: [{ eventType: 'payment.failed', paymentStatus: 'failed', failureReason: item.failureReason }],
    existingActions: [],
    confidenceThreshold,
    isTestMode,
    now
  });

  const executionEligible = policy.decision === 'ALLOW' && (strategy?.isLiveExecutable || false);
  const escalated = policy.decision === 'REVIEW';
  const stopped = policy.decision === 'BLOCK' || stopping.stopped;

  return {
    caseId: item.id,
    paymentId: item.paymentId,
    amount: item.amount,
    currency: item.currency,
    riskLevel: item.riskLevel,
    failureReason: item.failureReason,
    strategy: candidateAction,
    executionMode: strategy?.executionMode || EXECUTION_MODES.SIMULATED,
    isLiveExecutable: Boolean(strategy?.isLiveExecutable),
    estimatedProbability: baseProb,
    ervPaise,
    policyDecision: policy.decision,
    policyReasons: policy.reasons,
    stoppingReason: stopping.stopped ? stopping.reasonCode : null,
    executionEligible,
    escalated,
    stopped
  };
}

/**
 * Runs a complete portfolio evaluation over a batch of cases.
 *
 * @param {Array} rawCases - Batch of cases
 * @param {object} options
 * @returns {object} Comprehensive batch evaluation metrics
 */
function evaluateBatch(rawCases, options = {}) {
  const { maxBatchSize = MAX_BATCH_SIZE, isTestMode = true, confidenceThreshold, now = () => new Date(), simulateRecoveries = false } = options;
  const cases = validateBatchInput(rawCases, { maxBatchSize });

  if (cases.length === 0) {
    return {
      dataProvenance: 'SIMULATED_BATCH',
      isSimulated: true,
      evaluatedAt: now().toISOString(),
      totalCases: 0,
      totalRevenueAtRiskPaise: 0,
      totalRevenueAtRiskFormatted: '₹0',
      diagnosedCases: 0,
      executionEligibleCases: 0,
      escalatedCases: 0,
      stoppedCases: 0,
      simulatedRecoveredCases: 0,
      simulatedRecoveredRevenuePaise: 0,
      simulatedRecoveredRevenueFormatted: '₹0',
      recoveryRate: 0,
      totalExpectedRecoveryValuePaise: 0,
      totalExpectedRecoveryValueFormatted: '₹0',
      averageExpectedRecoveryValuePaise: 0,
      strategyDistribution: {},
      stopReasonDistribution: {},
      escalationDistribution: {},
      riskLevelDistribution: {},
      highestRiskCases: [],
      highestValueRecoveries: [],
      itemEvaluations: []
    };
  }

  let totalRevenueAtRisk = 0;
  let totalERV = 0;
  let executionEligibleCount = 0;
  let escalatedCount = 0;
  let stoppedCount = 0;
  let simulatedRecoveredCount = 0;
  let simulatedRecoveredRevenue = 0;

  const strategyDistribution = {};
  const stopReasonDistribution = {};
  const escalationDistribution = {};
  const riskLevelDistribution = { HIGH: 0, MEDIUM: 0, LOW: 0 };
  const itemEvaluations = [];

  for (const item of cases) {
    totalRevenueAtRisk += item.amount;
    riskLevelDistribution[item.riskLevel] = (riskLevelDistribution[item.riskLevel] || 0) + 1;

    const evaluation = evaluateBatchItem(item, { isTestMode, confidenceThreshold, now });
    itemEvaluations.push(evaluation);

    totalERV += evaluation.ervPaise;

    // Strategy distribution
    const strat = evaluation.strategy;
    if (!strategyDistribution[strat]) {
      strategyDistribution[strat] = { count: 0, totalAmountPaise: 0, totalErvPaise: 0, executionMode: evaluation.executionMode };
    }
    strategyDistribution[strat].count++;
    strategyDistribution[strat].totalAmountPaise += evaluation.amount;
    strategyDistribution[strat].totalErvPaise += evaluation.ervPaise;

    if (evaluation.executionEligible) executionEligibleCount++;
    if (evaluation.escalated) {
      escalatedCount++;
      const escReason = evaluation.policyReasons[0] || 'MANUAL_REVIEW_REQUIRED';
      escalationDistribution[escReason] = (escalationDistribution[escReason] || 0) + 1;
    }
    if (evaluation.stopped) {
      stoppedCount++;
      const stopCode = evaluation.stoppingReason || 'POLICY_BLOCKED';
      stopReasonDistribution[stopCode] = (stopReasonDistribution[stopCode] || 0) + 1;
    }

    // Optional simulated recovery estimation
    if (simulateRecoveries && evaluation.policyDecision === 'ALLOW') {
      // Deterministic simulation based on estimated probability threshold
      if (evaluation.estimatedProbability >= 0.4) {
        simulatedRecoveredCount++;
        simulatedRecoveredRevenue += evaluation.amount;
      }
    }
  }

  const recoveryRate = totalRevenueAtRisk > 0 ? Math.round((simulatedRecoveredRevenue / totalRevenueAtRisk) * 10000) / 10000 : 0;
  const avgERV = Math.round(totalERV / cases.length);

  // Ranked summaries
  const highestRiskCases = [...itemEvaluations]
    .filter((e) => e.riskLevel === 'HIGH' || e.amount >= 1000000)
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 10);

  const highestValueRecoveries = [...itemEvaluations]
    .sort((a, b) => b.ervPaise - a.ervPaise)
    .slice(0, 10);

  return {
    dataProvenance: 'SIMULATED_BATCH',
    isSimulated: true,
    evaluationNotice: 'Figures represent synthetic portfolio simulation and deterministic policy projection. No live Razorpay financial transactions were created.',
    heuristicVersion: HEURISTIC_VERSION,
    evaluatedAt: now().toISOString(),
    totalCases: cases.length,
    totalRevenueAtRiskPaise: totalRevenueAtRisk,
    totalRevenueAtRiskFormatted: `₹${(totalRevenueAtRisk / 100).toLocaleString('en-IN')}`,
    diagnosedCases: cases.length,
    executionEligibleCases: executionEligibleCount,
    escalatedCases: escalatedCount,
    stoppedCases: stoppedCount,
    simulatedRecoveredCases: simulatedRecoveredCount,
    simulatedRecoveredRevenuePaise: simulatedRecoveredRevenue,
    simulatedRecoveredRevenueFormatted: `₹${(simulatedRecoveredRevenue / 100).toLocaleString('en-IN')}`,
    recoveryRate,
    totalExpectedRecoveryValuePaise: totalERV,
    totalExpectedRecoveryValueFormatted: `₹${(totalERV / 100).toLocaleString('en-IN')}`,
    averageExpectedRecoveryValuePaise: avgERV,
    averageExpectedRecoveryValueFormatted: `₹${(avgERV / 100).toLocaleString('en-IN')}`,
    strategyDistribution,
    stopReasonDistribution,
    escalationDistribution,
    riskLevelDistribution,
    highestRiskCases,
    highestValueRecoveries,
    itemEvaluations
  };
}

module.exports = {
  evaluateBatch,
  evaluateBatchItem,
  validateBatchInput,
  BatchValidationError,
  MAX_BATCH_SIZE
};
